### ISSUE TITLE
Resource not found log spam on 1.20.5 Fabric

### ISSUE THREAD

**Issue by lineargraph** [shedaniel/error-notifier#3]
The following log lines are repeated forever:

```
java.lang.RuntimeException: Resource not found: /assets/minecraft/textures/gui/options_background.png
	at me.shedaniel.errornotifier.fabric.ErrorNotifierPlatformImpl.lambda$getResourceResolver$0(ErrorNotifierPlatformImpl.java:30)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.lambda$registerTexture$0(EarlyGraphics.java:178)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.registerTexture(EarlyGraphics.java:185)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.registerTexture(EarlyGraphics.java:178)
	at me.shedaniel.errornotifier.launch.EarlyGraphics._bindTexture(EarlyGraphics.java:204)
	at me.shedaniel.errornotifier.launch.EarlyGraphics.bindTexture(EarlyGraphics.java:106)
	at me.shedaniel.errornotifier.client.DynamicErrorFreeEntryListWidget.renderBackBackground(DynamicErrorFreeEntryListWidget.java:122)
	at me.shedaniel.errornotifier.client.DynamicErrorFreeEntryListWidget.render(DynamicErrorFreeEntryListWidget.java:132)
	at me.shedaniel.errornotifier.client.ErrorRenderer.render(ErrorRenderer.java:42)
	at me.shedaniel.errornotifier.launch.EarlyWindow.render(EarlyWindow.java:235)
	at me.shedaniel.errornotifier.launch.EarlyWindow.renderWindow(EarlyWindow.java:226)
	at me.shedaniel.errornotifier.launch.EarlyWindow.start(EarlyWindow.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at me.shedaniel.errornotifier.ErrorNotifier.init(ErrorNotifier.java:43)
	at me.shedaniel.errornotifier.fabric.ErrorNotifierFabric.onPreLaunch(ErrorNotifierFabric.java:11)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

**Comment by ranixcz** [comment]
solved i was missing dependency which fabric did not told me

**Comment by Poopooracoocoo** [comment]
@ranixcz This is still a bug in Error Notifier. Shedaniel doesn't use Fabric's dependency system on purpose.

**Comment by lineargraph** [comment]
Fixed in https://github.com/shedaniel/error-notifier/commit/b5952c3bae86052100970c32a9b821950d66280f
